Changed error reporting in `check-cert-encoding`
Changed error reporting so that the `check-cert-encoding` function
output its own error message, instead of using the `error` function.

I did this so that the error could be reported to the user, and the
script then exit. Athough this would prevent the further tests being
run, there was no benefit in proceeding with those tests.
Proeeding to run the further tests, against a certificate with the wrong
encoding, would result in numerous OpenSSL error messages, which would
only confuse, rather than help, the user.

diff --git a/bin/katello-certs-check b/bin/katello-certs-check
--- a/bin/katello-certs-check
+++ b/bin/katello-certs-check
@@ -120,11 +120,12 @@ function check-cert-encoding () {
     else
         openssl x509 -inform der -in $CERT_FILE -noout -text &> /dev/null
         if [ $? == "0" ]; then
-            error 8 "The server certificate is in DER encoding, which is not
-            compatible. Convert the certificate to PEM encoding,
-            then test it again."
+            printf "[FAIL]\n"
+            printf "The server certificate is in DER encoding, which is incompatible.\n"
+            printf "Convert the certificate to PEM encoding, then test it again.\n"
+            exit 8
         else
-            error 9 "The server certificate is in an invalid encoding."
+            error 9 "The encoding of the server certificate is either invalid or unable to be read."
         fi
     fi
 }
